pipeline {
    agent any

    environment {
        IMAGE_NAME = "flask-devops-app"
        DOCKERHUB_REPO = "shivix/flask-devops-app"
        CONTAINER_NAME = "flask-demo"
    }

    stages {

        stage('Checkout Code') {
            steps {
                echo 'Repository already checked out by Jenkins.'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('app') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Tag Docker Image') {
            steps {
                sh '''
                docker tag $IMAGE_NAME $DOCKERHUB_REPO:latest
                docker tag $IMAGE_NAME $DOCKERHUB_REPO:$BUILD_NUMBER
                '''
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login \
                    -u "$DOCKER_USER" \
                    --password-stdin
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh '''
                docker push $DOCKERHUB_REPO:latest
                docker push $DOCKERHUB_REPO:$BUILD_NUMBER
                '''
            }
        }

        stage('Stop Existing Container') {
            steps {
                sh 'docker rm -f $CONTAINER_NAME || true'
            }
        }

        stage('Run Docker Container') {
            steps {
                dir('app') {
                    sh '''
                    docker run -d \
                      --name $CONTAINER_NAME \
                      -p 5000:5000 \
                      $IMAGE_NAME
                    '''
                }
            }
        }

    }

    post {
        success {
            echo 'Application deployed successfully!'
        }

        failure {
            echo 'Pipeline failed.'
        }

        always {
            sh 'docker logout || true'
        }
    }
}

// trying webhook now
// testing pipeline with webhook