pipeline {
    agent any

    environment {
        IMAGE_NAME = "flask-devops-app"
        CONTAINER_NAME = "flask-demo"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('app') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Stop Existing Container') {
            steps {
                sh 'docker rm -f $CONTAINER_NAME || true'
            }
        }

        stage('Run Docker Container') {
            steps {
                dir('app') {
                    sh '''
                    docker run -d \
                      --name $CONTAINER_NAME \
                      -p 5000:5000 \
                      $IMAGE_NAME
                    '''
                }
            }
        }

    }

    post {
        success {
            echo 'Application deployed successfully!'
        }

        failure {
            echo 'Pipeline failed.'
        }
    }
}