---
- name: Create Jenkins home directory
  file:
    path: /opt/jenkins_home
    state: directory
    owner: "1000"
    group: "1000"
    mode: '0755'

- name: Pull Jenkins image
  shell: docker pull jenkins/jenkins:lts

- name: Run Jenkins container
  shell: |
    docker run -d \
      --name jenkins \
      --restart unless-stopped \
      -p 8080:8080 \
      -p 50000:50000 \
      -v /opt/jenkins_home:/var/jenkins_home \
      jenkins/jenkins:lts
  ignore_errors: yes