---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Start Docker Service
  service:
    name: docker
    state: started

- name: Enable Docker Service
  service:
    name: docker
    enabled: yes

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes